In [2]:
import numpy as np

## За что не любят Python и любят C++?

In [2]:
a = list(range(1_000_000))

In [3]:
%%timeit
[e * e for e in a]

72.6 ms ± 3.48 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [4]:
a = np.arange(1_000_000)

In [5]:
%%timeit
a * a

2.3 ms ± 42.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Создание массивов

In [6]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [7]:
a = np.array([1, 2, 3, 4, 5], dtype=np.float64)
a

array([ 1.,  2.,  3.,  4.,  5.])

In [8]:
a = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 0]], dtype=float)
a

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9.,  0.]])

In [9]:
a.shape

(2, 5)

In [10]:
a.ndim

2

In [11]:
a.dtype

dtype('float64')

In [12]:
a.astype(int)

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [13]:
b = a.reshape(5, 2)
b

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9.,  0.]])

In [14]:
a.reshape(-1, 2)

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9.,  0.]])

In [15]:
b = a.reshape(5, -1)

a[0, 1] = -10
b

array([[  1., -10.],
       [  3.,   4.],
       [  5.,   6.],
       [  7.,   8.],
       [  9.,   0.]])

In [16]:
a.flatten()

array([  1., -10.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,   0.])

In [17]:
a.T

array([[  1.,   6.],
       [-10.,   7.],
       [  3.,   8.],
       [  4.,   9.],
       [  5.,   0.]])

### Создание массивов с особыми свойствами

In [18]:
np.zeros(shape=(3, 2))

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [19]:
np.zeros_like(a)

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [20]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [21]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [22]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [24]:
np.arange(1, 10, 0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])

In [25]:
np.linspace(0, 1, 5, endpoint=True)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

### Избегаем ненужного копирования

In [26]:
a = np.array([1, 2, 3, 4, 5], dtype=np.float32)
b = np.asarray(a)
c = np.array(a)

b, c

(array([ 1.,  2.,  3.,  4.,  5.], dtype=float32),
 array([ 1.,  2.,  3.,  4.,  5.], dtype=float32))

In [27]:
a[0] = 0
b, c

(array([ 0.,  2.,  3.,  4.,  5.], dtype=float32),
 array([ 1.,  2.,  3.,  4.,  5.], dtype=float32))

In [28]:
a = np.array([1, 2, 3, 4, 5], dtype=np.float32)
b = np.asarray(a, dtype=np.int32)
c = np.array(a)

a, b, c

(array([ 1.,  2.,  3.,  4.,  5.], dtype=float32),
 array([1, 2, 3, 4, 5], dtype=int32),
 array([ 1.,  2.,  3.,  4.,  5.], dtype=float32))

In [29]:
a[0] = 0
a, b, c

(array([ 0.,  2.,  3.,  4.,  5.], dtype=float32),
 array([1, 2, 3, 4, 5], dtype=int32),
 array([ 1.,  2.,  3.,  4.,  5.], dtype=float32))

## Поэлементные операции над массивами

### Унарные операции

In [30]:
a = np.arange(10).reshape(2, -1)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
a ** 3

array([[  0,   1,   8,  27,  64],
       [125, 216, 343, 512, 729]])

In [32]:
a + 2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

In [33]:
2 * a

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [34]:
2 ** a

array([[  1,   2,   4,   8,  16],
       [ 32,  64, 128, 256, 512]])

In [35]:
np.sqrt(a)

array([[ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ],
       [ 2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ]])

In [36]:
np.exp(a)

array([[  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
          2.00855369e+01,   5.45981500e+01],
       [  1.48413159e+02,   4.03428793e+02,   1.09663316e+03,
          2.98095799e+03,   8.10308393e+03]])

In [37]:
np.log2(1 + a)

array([[ 0.        ,  1.        ,  1.5849625 ,  2.        ,  2.32192809],
       [ 2.5849625 ,  2.80735492,  3.        ,  3.169925  ,  3.32192809]])

In [38]:
np.sin(a)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849]])

In [39]:
a > 0

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]], dtype=bool)

### Статистические операции

In [40]:
np.random.seed(5555)
a = np.random.randint(0, 10, size=(3, 7))

a

array([[2, 3, 0, 5, 2, 0, 3],
       [8, 8, 0, 7, 1, 5, 3],
       [0, 1, 6, 2, 1, 4, 5]])

In [41]:
a.min(), a.max(), a.sum(), a.argmax()

(0, 8, 66, 7)

In [42]:
np.min(a), np.max(a), np.sum(a), np.argmax(a)

(0, 8, 66, 7)

In [43]:
a.max(axis=0)

array([8, 8, 6, 7, 2, 5, 5])

In [44]:
a.sum(axis=1)

array([15, 32, 19])

### Унарные операции над булевыми массивами

In [45]:
a = np.asarray([True, True, False, False, True])
a

array([ True,  True, False, False,  True], dtype=bool)

In [46]:
a.any(), np.any(a), any(a)

(True, True, True)

In [47]:
a.all(), np.all(a), all(a)

(False, False, False)

In [48]:
a = np.asarray([[True, True,  False, False, True ],
                [True, False, False, True,  False]])
a

array([[ True,  True, False, False,  True],
       [ True, False, False,  True, False]], dtype=bool)

In [49]:
a.any(axis=0)

array([ True,  True, False,  True,  True], dtype=bool)

In [50]:
a.all(axis=1)

array([False, False], dtype=bool)

In [51]:
np.logical_not(a)

array([[False, False,  True,  True, False],
       [False,  True,  True, False,  True]], dtype=bool)

In [52]:
# битовые операции

~a

array([[False, False,  True,  True, False],
       [False,  True,  True, False,  True]], dtype=bool)

### Бинарные операции

In [53]:
a

array([[ True,  True, False, False,  True],
       [ True, False, False,  True, False]], dtype=bool)

In [54]:
np.random.seed(4968)
b = np.random.randint(0, 10, size=a.shape)

b

array([[3, 0, 8, 1, 3],
       [1, 0, 2, 7, 8]])

In [55]:
a * b

array([[3, 0, 0, 0, 3],
       [1, 0, 0, 7, 0]])

In [56]:
a + b

array([[4, 1, 8, 1, 4],
       [2, 0, 2, 8, 8]])

In [57]:
a

array([[ True,  True, False, False,  True],
       [ True, False, False,  True, False]], dtype=bool)

In [58]:
b

array([[3, 0, 8, 1, 3],
       [1, 0, 2, 7, 8]])

In [59]:
np.fmax(a, b)

array([[3, 1, 8, 1, 3],
       [1, 0, 2, 7, 8]])

In [60]:
a > b

array([[False,  True, False, False, False],
       [False, False, False, False, False]], dtype=bool)

### Бинарные операции над булевыми массивами

In [61]:
a = np.asarray([True, True,  False, False, True ])
b = np.asarray([True, False, False, True,  False])

a, b

(array([ True,  True, False, False,  True], dtype=bool),
 array([ True, False, False,  True, False], dtype=bool))

In [62]:
np.logical_and(a, b), np.logical_or(a, b), np.logical_xor(a, b)

(array([ True, False, False, False, False], dtype=bool),
 array([ True,  True, False,  True,  True], dtype=bool),
 array([False,  True, False,  True,  True], dtype=bool))

In [63]:
# битовые операции

a & b, a | b, a ^ b

(array([ True, False, False, False, False], dtype=bool),
 array([ True,  True, False,  True,  True], dtype=bool),
 array([False,  True, False,  True,  True], dtype=bool))

### Более хитрые примеры бинарных операций 😏

In [64]:
a = np.arange(30).reshape(3, -1)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [65]:
b = np.arange(a.shape[1])
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
a + b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [10, 12, 14, 16, 18, 20, 22, 24, 26, 28],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38]])

In [67]:
b = np.arange(a.shape[0])
b

array([0, 1, 2])

In [68]:
# Ooops!

a + b

ValueError: operands could not be broadcast together with shapes (3,10) (3,) 

In [69]:
b = np.arange(a.shape[0]).reshape(a.shape[0], -1)
b

array([[0],
       [1],
       [2]])

In [70]:
a + b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

### И еще более хитрые примеры бинарных операций 🤯

In [3]:
a = np.arange(6).reshape(1, -1)
b = np.arange(5).reshape(-1, 1)

In [4]:
a

array([[0, 1, 2, 3, 4, 5]])

In [5]:
b

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [6]:
a + b

array([[0, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6, 7],
       [3, 4, 5, 6, 7, 8],
       [4, 5, 6, 7, 8, 9]])

In [75]:
a >= b

array([[ True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [False, False,  True,  True,  True],
       [False, False, False,  True,  True],
       [False, False, False, False,  True]], dtype=bool)

Поэтому, как говорили на уроках физики:
<center><h3>Не забывай следить за размерностью!</h3></center>

Чуть более подробное описание [правил](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) приведения размерностей.

## Матричные операции над массивами

In [76]:
av = np.arange(1, 5).reshape(-1, 2)
av

array([[1, 2],
       [3, 4]])

In [77]:
bv = np.array([[1, 2], [-2, 1]])
bv

array([[ 1,  2],
       [-2,  1]])

In [78]:
av * bv

array([[ 1,  4],
       [-6,  4]])

In [79]:
np.matmul(av, bv)

array([[-3,  4],
       [-5, 10]])

In [80]:
# no copy, pls

am = np.asmatrix(av)
bm = np.asmatrix(bv)

am

matrix([[1, 2],
        [3, 4]])

In [81]:
am * bm

matrix([[-3,  4],
        [-5, 10]])

In [82]:
av ** 2

array([[ 1,  4],
       [ 9, 16]])

In [83]:
am ** 2

matrix([[ 7, 10],
        [15, 22]])

Все самое важное для линейной алгебры:

https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

## Индексация в одномерных массивах

**Замечание:** индексация может быть использована не только для получения значений, но и для их присвоения.

In [84]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [85]:
a[0], a[5], a[len(a) - 1]

(0, 5, 14)

### Отрицательные индексы

In [86]:
a[len(a) - 1], a[-1]

(14, 14)

In [87]:
a[len(a) - 5], a[-5]

(10, 10)

### Срезы (slice)

**Общее правило:** `массив[первый индекс:последний индекс:шаг]`.

Значения по-умолчанию:
    * первый индекс = 0; 
    * последний индекс = len(массив);
    * шаг = 1;
    
`последний индекс` не включается.

In [88]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Взять первые 5 элементов.

In [89]:
variants = [ a[0:5:1], a[0:5], a[:5] ]

print(*map(repr, variants), sep='\n')

array([0, 1, 2, 3, 4])
array([0, 1, 2, 3, 4])
array([0, 1, 2, 3, 4])


Взять все элементы, стоящих на четных позициях.

In [90]:
variants = [ a[0:len(a):2], a[0::2], a[::2] ]

print(*map(repr, variants), sep='\n')

array([ 0,  2,  4,  6,  8, 10, 12, 14])
array([ 0,  2,  4,  6,  8, 10, 12, 14])
array([ 0,  2,  4,  6,  8, 10, 12, 14])


Взять все элементы, стоящие на нечетных позициях.

In [91]:
variants = [ a[1:len(a):2], a[1::2] ]

print(*map(repr, variants), sep='\n')

array([ 1,  3,  5,  7,  9, 11, 13])
array([ 1,  3,  5,  7,  9, 11, 13])


Взять все элементы с 3 по 12 (не включительно) с шагом 3.

In [92]:
variants = [ a[3:12:3], a[3:-3:3] ]

print(*map(repr, variants), sep='\n')

array([3, 6, 9])
array([3, 6, 9])


Взять все элементы с 3 по 12 (включительно) с шагом 3 в обратном порядке.

In [93]:
variants = [ a[3:13:3][::-1], a[12:2:-3], a[-3:2:-3] ]

print(*map(repr, variants), sep='\n')

array([12,  9,  6,  3])
array([12,  9,  6,  3])
array([12,  9,  6,  3])


### Булева индексация (маски)

In [94]:
np.random.seed(1234)
a = np.random.randint(-2, 7, 34)
a

array([ 1,  4,  3,  2,  6, -1,  5,  4,  6, -2,  3, -2,  4,  0, -2,  3,  0,
        4,  1,  5, -2, -2,  1,  0,  1, -1,  1, -1,  1,  5, -1,  5,  2, -2])

Найти все отрицательные элементы.

In [95]:
a < 0

array([False, False, False, False, False,  True, False, False, False,
        True, False,  True, False, False,  True, False, False, False,
       False, False,  True,  True, False, False, False,  True, False,
        True, False, False,  True, False, False,  True], dtype=bool)

In [96]:
a[a < 0]

array([-1, -2, -2, -2, -2, -2, -1, -1, -1, -2])

Найти все элементы, кратные 3-м.

In [97]:
variants = [ a[a % 3 == 0], a[np.logical_not(a % 3)], a[~((a % 3).astype(bool))] ]

print(*map(repr, variants), sep='\n')

array([3, 6, 6, 3, 0, 3, 0, 0])
array([3, 6, 6, 3, 0, 3, 0, 0])
array([3, 6, 6, 3, 0, 3, 0, 0])


In [98]:
np.random.seed(1234)
a = np.random.randint(0, 9, 23)
a

array([3, 6, 5, 4, 8, 1, 7, 6, 8, 0, 5, 0, 6, 2, 0, 5, 2, 6, 3, 7, 0, 0, 3])

Найти все элементы, кратные или 3, или 5.

In [99]:
mask_3 = a % 3 == 0
mask_5 = a % 5 == 0

variants = [ a[np.logical_or(mask_3, mask_5)], a[mask_3 | mask_5] ]

print(*map(repr, variants), sep='\n')

array([3, 6, 5, 6, 0, 5, 0, 6, 0, 5, 6, 3, 0, 0, 3])
array([3, 6, 5, 6, 0, 5, 0, 6, 0, 5, 6, 3, 0, 0, 3])


Найти все элементы, кратные и 2, и 3.

In [100]:
mask_2 = a % 2 == 0
mask_3 = a % 3 == 0

variants = [ a[np.logical_and(mask_2, mask_3)], a[mask_2 & mask_3], a[a % 6 == 0] ]

print(*map(repr, variants), sep='\n')

array([6, 6, 0, 0, 6, 0, 6, 0, 0])
array([6, 6, 0, 0, 6, 0, 6, 0, 0])
array([6, 6, 0, 0, 6, 0, 6, 0, 0])


## Индексация в многомерных массивах

In [101]:
a = np.arange(30).reshape(5, -1)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [102]:
# плохой способ, мы работаем с numpy-массивами, а не со списками

a[0][0], a[0][2], a[1][1], a[-1][-2]

(0, 2, 7, 28)

In [103]:
# хороший способ

a[0,0], a[0,2], a[1,1], a[-1,-2]

(0, 2, 7, 28)

Получить строку с индексом 2.

In [104]:
variants = [ a[2], a[2,:] ]

print(*map(repr, variants), sep='\n')

array([12, 13, 14, 15, 16, 17])
array([12, 13, 14, 15, 16, 17])


Получить столбец с индексом 3.

In [105]:
a[:,3]

array([ 3,  9, 15, 21, 27])

Получить все элементы, стоящие в четных столбцах.

In [106]:
a[:,::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

Получить все элементы, стоящие в первой (0-й) строке и нечетных стоблцах.

In [107]:
a[0,1::2]

array([1, 3, 5])

Получить все элементы `a[i,j]`, такие что:
    * i -- нечетные;
    * j -- дающие остаток 2 при делении на 3;
индексация по строкам, должна быть обратной.

In [108]:
a[1::2,2::3][::-1]

array([[20, 23],
       [ 8, 11]])

In [109]:
np.random.seed(2238)

a = np.random.randint(-5, 5, size=(5, 5))
a

array([[ 3,  2, -1, -3,  4],
       [ 3, -2, -2, -2, -5],
       [ 3,  2, -1,  1,  1],
       [ 2,  0,  4, -2,  0],
       [ 0,  4,  1,  2,  4]])

Получите строки, в которых есть хотя бы один 0.

In [110]:
a[(a == 0).any(axis=1)]

array([[ 2,  0,  4, -2,  0],
       [ 0,  4,  1,  2,  4]])

Получите столбцы, в которых число положительных элементов больше числа отрицательных.

In [111]:
a[:, (a > 0).sum(axis=0) > (a < 0).sum(axis=0)]

array([[ 3,  2,  4],
       [ 3, -2, -5],
       [ 3,  2,  1],
       [ 2,  0,  0],
       [ 0,  4,  4]])

Получить положительные элементы.

In [112]:
a[a > 0]

array([3, 2, 4, 3, 3, 2, 1, 1, 2, 4, 4, 1, 2, 4])

Получить индексы положительных элементов.

In [113]:
np.where(a > 0)

(array([0, 0, 0, 1, 2, 2, 2, 2, 3, 3, 4, 4, 4, 4]),
 array([0, 1, 4, 0, 0, 1, 3, 4, 0, 2, 1, 2, 3, 4]))

In [114]:
a[np.where(a > 0)]

array([3, 2, 4, 3, 3, 2, 1, 1, 2, 4, 4, 1, 2, 4])

In [115]:
# трансформируем координаты

list(zip(*np.where(a > 0)))

[(0, 0),
 (0, 1),
 (0, 4),
 (1, 0),
 (2, 0),
 (2, 1),
 (2, 3),
 (2, 4),
 (3, 0),
 (3, 2),
 (4, 1),
 (4, 2),
 (4, 3),
 (4, 4)]

In [116]:
# извлекаем значения по этим координатам

# пример исключтельно иллюстративный, правильный способ описан выше:
# a[a > 0]

[a[i,j] for i, j in zip(*np.where(a > 0))]

[3, 2, 4, 3, 3, 2, 1, 1, 2, 4, 4, 1, 2, 4]

### Fancy Indexing

In [117]:
a

array([[ 3,  2, -1, -3,  4],
       [ 3, -2, -2, -2, -5],
       [ 3,  2, -1,  1,  1],
       [ 2,  0,  4, -2,  0],
       [ 0,  4,  1,  2,  4]])

Получить 2, 4 и 3 строки.

In [118]:
a[[2,4,3]]

array([[ 3,  2, -1,  1,  1],
       [ 0,  4,  1,  2,  4],
       [ 2,  0,  4, -2,  0]])

Получить элементы 2, 4, 3 строках и в 0-м и последнем столбце. 

In [119]:
# Ooops!

a[[2, 4, 3],[0, -1]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [120]:
a[[2, 4, 3]][:,[0, -1]]

array([[3, 1],
       [0, 4],
       [2, 0]])

In [121]:
a[np.ix_([2, 4, 3], [0, -1])]

array([[3, 1],
       [0, 4],
       [2, 0]])

## О чём ещё полезно знать?

### Генерация случайных чисел

In [122]:
np.random.rand(10)

array([ 0.22024735,  0.88293447,  0.69184538,  0.00523532,  0.48975893,
        0.78255915,  0.4244878 ,  0.45827732,  0.0449126 ,  0.5361042 ])

In [123]:
np.random.randint(0, 10, 10)

array([8, 1, 5, 3, 8, 9, 7, 2, 1, 0])

In [124]:
np.random.permutation(10)

array([6, 8, 5, 4, 9, 3, 1, 0, 2, 7])

In [125]:
np.random.choice(10, size=10)

array([4, 0, 2, 5, 7, 9, 3, 5, 4, 4])

### Сортировка

In [126]:
np.random.seed(4445)

a = np.random.choice(10, size=(3, 10))
a

array([[6, 0, 3, 1, 5, 3, 1, 6, 6, 4],
       [5, 3, 7, 1, 3, 0, 5, 5, 3, 6],
       [4, 1, 1, 0, 4, 3, 3, 3, 2, 1]])

In [127]:
np.sort(a.ravel())

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 5, 5,
       5, 5, 6, 6, 6, 6, 7])

In [128]:
a.sort(axis=0)
a

array([[4, 0, 1, 0, 3, 0, 1, 3, 2, 1],
       [5, 1, 3, 1, 4, 3, 3, 5, 3, 4],
       [6, 3, 7, 1, 5, 3, 5, 6, 6, 6]])

In [129]:
a.sort(axis=1)
a

array([[0, 0, 0, 1, 1, 1, 2, 3, 3, 4],
       [1, 1, 3, 3, 3, 3, 4, 4, 5, 5],
       [1, 3, 3, 5, 5, 6, 6, 6, 6, 7]])

In [130]:
np.random.seed(4445)

a = np.random.choice(10, size=(3, 10))
a

array([[6, 0, 3, 1, 5, 3, 1, 6, 6, 4],
       [5, 3, 7, 1, 3, 0, 5, 5, 3, 6],
       [4, 1, 1, 0, 4, 3, 3, 3, 2, 1]])

In [131]:
a.argsort(axis=0)

array([[2, 0, 2, 2, 1, 1, 0, 2, 2, 2],
       [1, 2, 0, 0, 2, 0, 2, 1, 1, 0],
       [0, 1, 1, 1, 0, 2, 1, 0, 0, 1]])

In [132]:
a.argsort(axis=1)

array([[1, 3, 6, 2, 5, 9, 4, 0, 7, 8],
       [5, 3, 1, 4, 8, 0, 6, 7, 9, 2],
       [3, 1, 2, 9, 8, 5, 6, 7, 0, 4]])

### Получение уникальных элементов

In [133]:
np.unique(a)

array([0, 1, 2, 3, 4, 5, 6, 7])